# FROM ubuntu:18.04
 
# # COPY . /home/
 
# # WORKDIR /home/
 
# # RUN chmod 775 ./script/*.sh
 
# # RUN ./script/before_installation.sh
 
# # RUN ./script/installation.sh
 
# ENTRYPOINT ["python3" , "app.py"]

# FROM python:slim

# RUN mkdir ./opt/service_1

# COPY . /opt/service_1

# WORKDIR /opt/service_1

# RUN pip3 install -r requirements.txt