    version: "3.7"
    services: 
      
      service_1: 
        build: 
            context: ./service_1/
            dockerfile: Dockerfile
        ports: 
          - "5000:5000"
        networks:
            - hifza_network_

      service_2: 
        build: 
            context: ./service_2/
            dockerfile: Dockerfile
        networks:
            - hifza_network_

      service_3: 
        build: 
            context: ./service_3/
            dockerfile: Dockerfile
        networks:
            - hifza_network_

      service_4: 
        build: 
            context: ./service_4/
            dockerfile: Dockerfile
        networks:
            - hifza_network_
            
    networks:
      hifza_network_:
        driver: bridge
  


