- name: install docker to worker node
  hosts: servers
  become: true
  roles:
    - docker-installation

- name: install docker to local manager node
  hosts: localhost
  become: true
  roles:
    - docker-installation

- name: initialise docker swarm 
  hosts: localhost
  become: true
  roles:
    - docker-swarm-init

- name: add workers to the swarm 
  hosts: swarm-workers
  become: true
  roles:
    - docker-swarm-add-workers

